---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: foo
spec:
  parentRefs:
  - name: eg
  hostnames: ["www.example.com"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /foo              # This is the path that will be protected by OIDC
    backendRefs:
    - name: backend
      port: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak
spec:
  parentRefs:
  - name: eg
  hostnames: ["keycloak"]
  rules:
  - backendRefs:
    - name: keycloak
      port: 443
---
apiVersion: v1
kind: Secret
metadata:
  name: oidctest-secret
data:
  client-secret: b2lkY3Rlc3QtY2xpZW50LXNlY3JldA==   # base64 encoding of "oidctest-client-secret"
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: keycloak-oidc
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: foo
  oidc:
    provider:
      backendRefs:
      - group: gateway.envoyproxy.io
        kind: Backend
        name: backend-keycloak
        port: 443
      backendSettings:
        retry:
          numRetries: 3
          perRetry:
            backOff:
              baseInterval: 1s
              maxInterval: 5s
          retryOn:
            triggers: ["5xx", "gateway-error", "reset"]
      issuer: "https://keycloak.default/realms/master"
    clientID: "oidctest"
    clientSecret:
      name: "oidctest-secret"
    redirectURL: "https://www.example.com/foo/oauth2/callback"
    logoutPath: "/foo/logout"
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: backend-keycloak
spec:
  endpoints:
  - fqdn:
      hostname: 'keycloak.default'
      port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: policy-btls-keycloak-backend
spec:
  targetRefs:
  - group: gateway.envoyproxy.io
    kind: Backend
    name: backend-keycloak
  validation:
    caCertificateRefs:
    - name: backend-tls-certificate
      group: ""
      kind: ConfigMap
    hostname: keycloak.default
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: policy-btls-keycloak-service
spec:
  targetRefs:
  - name: keycloak
    group: ""
    kind: Service
  validation:
    caCertificateRefs:
    - name: backend-tls-certificate
      group: ""
      kind: ConfigMap
    hostname: keycloak.default
---
apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDOzCCAiOgAwIBAgIURVwQUAAZQU8h3MIR9yEN0B/djA8wDQYJKoZIhvcNAQEL
    BQAwLTEVMBMGA1UECgwMZXhhbXBsZSBJbmMuMRQwEgYDVQQDDAtleGFtcGxlLmNv
    bTAeFw0yNTAzMDkxMzEwNTBaFw0zNTAzMDcxMzEwNTBaMC0xFTATBgNVBAoMDGV4
    YW1wbGUgSW5jLjEUMBIGA1UEAwwLZXhhbXBsZS5jb20wggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQCl8F6WqU1XCxTaXKiklTJqxjd1MmsekTZKdnAg06b2
    9B4p9Ytb6RE1z0aIvyiLm66cxv0LvER3dCK8KZMV1k/ZMyIIN9tNkmYoxJ2k1jx+
    P8lxBbwRi3YPO7MY0xdJ3r2TPJ4iTokBNywyAhiXg34z+GlIBxD5WJt17qeWr3OB
    1yUwtdjEPoGP7GrjArPPRxuQHU/sTBXExl02jmsYP8qPfx4c31zlYe+JtC39/P74
    QWYqo7Lsgp3UpwXpsdFMShty1fwRQH8jjvOu/MdldPvK1BbGrzpAjhph8FxQvFWx
    y/6vG26+3+w1CN+dwEREiDPCEFBzvJXVfvgbvRkMxYwhAgMBAAGjUzBRMB0GA1Ud
    DgQWBBRRVSv3tI2ibhcLYxrUHLvIk4yZQTAfBgNVHSMEGDAWgBRRVSv3tI2ibhcL
    YxrUHLvIk4yZQTAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAN
    BPlTHy+174jv1kYxDRfqt4scr+sX7OVG5cIIFGE6CXiZmycPpahnsf4QuAa7a6AH
    JwNnnNJkeFDqGAXo8y7sg+KSIVPmtJ8wKB1gyRUQImnWSjQUgiSDbOZQXcelI5et
    0P4UKLEvX3fbxf+7peP6Bd6vgcIsVdA8GQ/hRQKuDhWcDZ1F/waBdfcoRCfWLqLq
    xsKHGt5uZTOfseR9FU8Ni+//Ww7KpZk2iQMK5SZNRBWNKVgt2yR3+XyZwXtZecoo
    mPJFzo+OUvBjWt41NrjmthGXDJwr3+xbmk2PzsBLguyrKaBZLSUPXVPDqEjP4mHL
    ErwRCdDiiGKLt0VTAe9o
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: backend-tls-certificate
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  namespace: default
  name: response-override-foo
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: foo
  responseOverride:
    - match:
        statusCodes:
          - type: Value
            value: 403
      response:
        contentType: text/html
        body:
          type: Inline
          inline: |
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Access Denied</title>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
                <style>
                    body {
                        font-family: 'Inter', sans-serif;
                        display: flex;
                        justify-content: center;
                        align-items: center;
                        height: 100vh;
                        background: linear-gradient(to right, #141e30, #243b55);
                        color: white;
                        text-align: center;
                    }
                    .container {
                        background: rgba(255, 255, 255, 0.1);
                        padding: 60px;
                        border-radius: 20px;
                        box-shadow: 0 20px 50px rgba(0, 0, 0, 0.5);
                        width: 500px;
                        backdrop-filter: blur(15px);
                        display: flex;
                        flex-direction: column;
                        align-items: center;
                        animation: fadeIn 1s ease-in-out;
                    }
                    h1 {
                        font-size: 36px;
                        margin-bottom: 15px;
                        color: #ff6b6b;
                    }
                    p {
                        font-size: 18px;
                        font-weight: 400;
                        margin-bottom: 25px;
                    }
                    .btn {
                        background: #ff6b6b;
                        color: white;
                        border: none;
                        padding: 14px 32px;
                        margin-top: 20px;
                        border-radius: 50px;
                        cursor: pointer;
                        font-size: 18px;
                        font-weight: bold;
                        transition: all 0.3s ease-in-out;
                        display: flex;
                        align-items: center;
                        gap: 12px;
                    }
                    .btn:hover {
                        background: #ff4757;
                        transform: scale(1.1);
                    }
                    @keyframes fadeIn {
                        from { opacity: 0; transform: translateY(20px); }
                        to { opacity: 1; transform: translateY(0); }
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <h1><i class="fa fa-lock"></i> 🔒 Access Denied</h1>
                    <p>Oops! You do not have permission to view this page.</p>
                    <button class="btn" onclick="window.location.href='/'"><i class="fa fa-home"></i> Back to Home</button>
                </div>
            </body>
            </html>

    - match:
        statusCodes:
          - type: Value
            value: 200
      response:
        contentType: text/html
        body:
          type: Inline
          inline: |
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>🎉 Access Granted</title>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
                <style>
                    body {
                        font-family: 'Inter', sans-serif;
                        display: flex;
                        justify-content: center;
                        align-items: center;
                        height: 100vh;
                        background: linear-gradient(to right, #141e30, #243b55);
                        color: white;
                        text-align: center;
                    }
                    .container {
                        background: rgba(255, 255, 255, 0.1);
                        padding: 50px;
                        border-radius: 20px;
                        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.4);
                        width: 500px;
                        backdrop-filter: blur(20px);
                        display: flex;
                        flex-direction: column;
                        align-items: center;
                        animation: fadeIn 1s ease-in-out;
                    }
                    h1 {
                        font-size: 32px;
                        margin-bottom: 15px;
                    }
                    p {
                        font-size: 18px;
                        font-weight: 400;
                        margin-bottom: 25px;
                    }
                    pre {
                        background: rgba(255, 255, 255, 0.2);
                        padding: 20px;
                        border-radius: 10px;
                        text-align: left;
                        overflow-x: auto;
                        font-size: 14px;
                        width: 100%;
                        color: #ddd;
                    }
                    .btn {
                        background: #00c6ff;
                        color: white;
                        border: none;
                        padding: 14px 32px;
                        margin-top: 20px;
                        border-radius: 12px;
                        cursor: pointer;
                        font-size: 18px;
                        font-weight: bold;
                        transition: all 0.3s ease-in-out;
                        display: flex;
                        align-items: center;
                        gap: 12px;
                    }
                    .btn:hover {
                        background: #0082ca;
                        transform: scale(1.07);
                    }
                    @keyframes fadeIn {
                        from { opacity: 0; transform: translateY(20px); }
                        to { opacity: 1; transform: translateY(0); }
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <h1><i class="fa fa-check-circle"></i> 🎉 Access Granted</h1>
                    <p>Welcome, <strong><span id="username">Huabing Zhao</span></strong>! You are successfully authenticated.</p>
                    <pre id="user-info">{
                "name": "Huabing Zhao",
                "email": "zhaohuabing@gmail.com",
                "role": "Elite Member"
            }</pre>
                    <button class="btn" onclick="window.location.href='https://www.example.com/foo/logout'"><i class="fa fa-sign-out-alt"></i> Logout</button>
                </div>
            </body>
            </html>
